Switch to CustomRouteController from library-go
openshift/cluster-authentication-operator pull request #478
Opened 2021-09-01 09:13 UTC by slaskawi

https://issues.redhat.com/browse/AUTH-14

This is a proof for https://github.com/openshift/library-go/pull/1138

2021-09-01 09:14 UTC, slaskawi commented
/test all

2021-09-01 11:05 UTC, slaskawi commented
/retest all

2021-09-10 07:18 UTC, stlaz commented
/test e2e-operator

2021-09-13 08:41 UTC, slaskawi commented
On my box, the `TestCustomRouterCerts` test is fine. Let's give them a few more tries...

/retest

2021-09-15 10:55 UTC, slaskawi commented
/retest

2021-09-16 07:46 UTC, slaskawi commented
/retest

2021-10-01 10:28 UTC, stlaz requested changes

2021-10-01 10:28 UTC, stlaz commented on pkg/operator/starter.go
> +	"github.com/openshift/library-go/pkg/operator/resource/resourceread"
order

2021-10-04 13:45 UTC, slaskawi commented on pkg/operator/starter.go
> +	"github.com/openshift/library-go/pkg/operator/resource/resourceread"
Fixed.

2021-10-05 08:56 UTC, slaskawi commented
/retest

2022-03-04 17:12 UTC, closed without merging