Enabling logging of oauth-server
openshift/cluster-authentication-operator pull request #497
Opened 2021-10-11 21:04 UTC by EmilyM1

Will be adding Deployment changes to make volume for oauth-server audit logs

2021-10-12 07:11 UTC, stlaz requested changes
/hold

Should be marked as WIP

2021-10-12 07:11 UTC, stlaz commented on bindata/oauth-openshift/deployment.yaml
> +        - name: oauth-server-audit
incomplete mount description?

2021-10-12 07:11 UTC, stlaz commented on bindata/oauth-openshift/deployment.yaml
> +              readOnly: true
this does't make sense

2021-10-12 07:11 UTC, stlaz commented on bindata/oauth-openshift/deployment.yaml
> +            - name: oauth-server-audit
see if https://github.com/openshift/cluster-authentication-operator/blob/master/bindata/oauth-apiserver/deploy.yaml#L36-L51 is needed here, too

2021-10-12 23:00 UTC, EmilyM1 commented on bindata/oauth-openshift/deployment.yaml
> +        - name: oauth-server-audit
Yeah, just added WIP, very early stages here

2021-10-15 07:39 UTC, stlaz commented on bindata/oauth-openshift/deployment.yaml
> +              --audit-log-maxbackup=10 \
please explain

2021-11-17 23:10 UTC, EmilyM1 commented
closed in favor of https://github.com/openshift/cluster-authentication-operator/pull/507/

2021-11-17 23:10 UTC, closed without merging