CONSOLE-3322: Update cluster-authentication-operator not to go degraded without console
openshift/cluster-authentication-operator pull request #587
Opened 2022-10-28 21:14 UTC by bparees

2022-11-07 22:20 UTC, bparees commented
/retest-required

2022-11-08 18:45 UTC, stlaz requested changes

2022-11-08 18:45 UTC, stlaz commented on pkg/controllers/configobservation/configobservercontroller/observe_config_controller.go
> +		preRunCacheSynced = append(preRunCacheSynced, configInformer.Config().V1().Consoles().Informer().HasSynced)
I think this should be `listers.PreRunCachesSynced = append(listers.PreRunCachesSynced, ...` to make sure the above struct contains the right slice

2022-11-08 18:48 UTC, stlaz commented
/lgtm

2022-11-08 18:49 UTC, bparees commented
/hold cancel

2022-11-08 18:49 UTC, bparees commented
/cherry-pick release-4.12

2022-11-09 14:52 UTC, bparees commented
/jira refresh

2022-11-09 14:53 UTC, bparees commented
/jira refresh

2022-11-10 15:53 UTC, bparees commented
/retest-required

2022-11-10 18:36 UTC, merged

2022-11-11 11:39 UTC, jhadvig commented
🥳