AUTH-482: set required-scc for openshift workloads
openshift/cluster-authentication-operator pull request #656
Opened 2024-02-20 11:27 UTC by liouk

2024-02-20 17:03 UTC, liouk commented
Interestingly, the `oauth-openshift` pods were getting admitted with the `node-exporter` SCC (belongs to the [cluster-monitoring-operator](https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/node-exporter/security-context-constraints.yaml)) exactly because of the problem that AUTH-482 describes.

2024-02-21 15:50 UTC, liouk commented
/retest

2024-02-26 16:28 UTC, liouk commented
/retest-required

2024-02-28 10:48 UTC, liouk commented
/hold
need to verify SCC

2024-02-28 13:30 UTC, liouk commented
/hold cancel

2024-02-28 13:30 UTC, liouk commented
/retest

2024-03-06 16:10 UTC, ibihim commented on manifests/07_deployment.yaml
> +        openshift.io/required-scc: anyiud
`anyuid` is sufficient? Interesting. I've seen that in the cluster as well.

2024-03-06 16:11 UTC, ibihim commented
Could be a lgtm, but the tests look failed... 🤔

2024-03-13 08:42 UTC, liouk commented
/retest-required

2024-03-13 08:53 UTC, liouk commented
/retest

2024-03-13 14:40 UTC, stlaz requested changes

2024-04-24 11:40 UTC, liouk commented on pkg/operator/assets/bindata.go
> +        openshift.io/required-scc: privileged
Done in 76183e3db5ef956316fff6280e0c2c69e1f0a5b9

2024-04-25 08:05 UTC, stlaz commented on bindata/assets.go
> +//go:embed oauth-apiserver/* oauth-apiserver/RBAC/* oauth-openshift/*
//go:embed oauth-apiserver/* oauth-openshift/*

2024-04-25 08:28 UTC, stlaz commented
https://github.com/openshift/cluster-authentication-operator/blob/6214f1b9fc57d14d242eb4af8c31da727a61582a/pkg/dependencymagnet/dependencymagnet.go#L9
this dep magnet also seems to be ready to be removed

2024-04-25 12:15 UTC, liouk commented
/retest-required

2024-04-26 07:21 UTC, liouk commented
/retest-required

2024-04-30 09:20 UTC, liouk commented
debug commits dropped
/hold cancel

2024-04-30 10:26 UTC, stlaz commented
/lgtm

2024-04-30 10:32 UTC, merged