NO-JIRA: Several fixes for Keycloack IDP test
openshift/cluster-authentication-operator pull request #679
Opened 2024-06-21 09:33 UTC by vrutkovs

* run deployment instead of a pod
* ping Keycloack version to v25
* since Keycloak v25 `/health` is no longer exposed on public ports. Use deployment probes instead

2024-06-21 11:18 UTC, vrutkovs commented
/cc @liouk @ibihim

2024-06-24 11:35 UTC, liouk requested changes

2024-06-24 12:27 UTC, vrutkovs commented on test/library/idpdeployment.go
> +	if _, err := watchtools.UntilWithSync(timeLimitedCtx,
I think `deployPod` should do the basic wait (image pulling, container creation etc.) and other parts may want to add separate waits if necessary

2024-06-24 12:41 UTC, liouk commented
Re 41b65b49e75a4cc8752c2defd375166c36a8eaec, I'll make sure we keep an eye on Keycloak releases and update the test as necessary. Breaking tests would force us to get them fixed and adapt to the latest Keycloak version, but that's not necessary in this context; so better be safe than sorry :) 

/lgtm

2024-06-25 09:14 UTC, soltysh approved these changes
/label approved

2024-06-25 09:22 UTC, merged

2024-07-30 07:09 UTC, liouk commented
/cherry-pick release-4.16